### ISSUE TITLE
v5 Spring Roadmap

### ISSUE THREAD

**Issue by Arraying** [ib-ai/IB.ai#83]
This contains the roadmap of what needs to be done for the v5 rewrite.

- [ ] Entities 
  - [x] Guild settings 
  - [x] Tags 
  - [x] User join overrides 
  - [x] User roles
  - [x] User opts
  - [ ] The rest that will be added later
- [ ] Components (see README for status on these)
- [ ] Unit tests: entities equals, hashCode
- [ ] Integration tests: component service business logic
